swagger:
  enable: true
channelCodes: ce9d59ed0a62478090adc2a2a714216a

tianqi:
  url: https://www.tianqiapi.com
  appid: 18327832
  appsecret: c8AY0oB5
weather:
  d7_url: http://d7.weather.com.cn
  d1_url: http://d1.weather.com.cn
ws:
  key: WIOBZ-7MI6S-2RMOC-6FMTV-CMYLH-U2BB3
  url: https://apis.map.qq.com
